# Generated by Django 4.2.2 on 2023-11-14 17:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Image',
            new_name='SlideImage',
        ),
    ]
